### ISSUE TITLE
Cannot receive the message on another session

### ISSUE THREAD

**Issue by cooffeeRequired** [rossedlin/chat-laravel-pusher#9]
Before i copied your git i try inplement that to my project, but the issue is the totaly same, the code seems works but i cannot receive the message on another session and that happens also with your source..

PHP 8.3.6

"php": "8.3.*",
"guzzlehttp/guzzle": "7.5.0",
"laravel/framework": "9.52.4",
"laravel/sanctum": "3.2.1",
"laravel/tinker": "2.8.1",
"pusher/pusher-php-server": "7.2.2",
"sentry/sentry-laravel": "3.2.0"

Docker: 4.29.0 (145265)
WIN 11 PRO

**Comment by rossedlin** [comment]
Hey,

A few obvious things you could check...
In your .env file

BROADCAST_DRIVER=**pusher**
QUEUE_CONNECTION=**sync**

Make sure the following variables are set to the following.

Also, since Laravel v11 you need to include the **_config/broadcasting.php_**

https://github.com/rossedlin/chat-laravel-pusher/blob/master/config/broadcasting.php

Let me know if that solves the problem! :)

**Comment by cooffeeRequired** [comment]
How can I include the broadcasting?

**Comment by cooffeeRequired** [comment]
![image](https://github.com/rossedlin/chat-laravel-pusher/assets/106232282/9a219dd1-d73a-47df-ab9d-b57f4ad21f03)

**Comment by cooffeeRequired** [comment]
![image](https://github.com/rossedlin/chat-laravel-pusher/assets/106232282/c2a9f5a0-bab1-4e1e-a010-5ed3345851be)
